### ISSUE TITLE
Table 'GRCh37.chromInfo' doesn't exist // ERROR: chrom "14" not found in genome file. Exiting.

### ISSUE THREAD

**Issue by Ekomshiro** [YeoLab/outrigger#89]
### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Alignwith STAR (OK) using Ensembl GRCh37 primary assembly and gtf
2. outrigger index with the same gtf used by STAR (OK)
3. outrigger validate with the same .fa used by STAR

**Expected behavior:** 
This is my first run, so I'm not sure..
But based on the error message it seems that it's looking for the chromInfo file and can't find it. Then it tries to get the chromInfo file from UCSC genome browser, but since the Ensembl naming convention uses "14" instead of "chr14" it can't find it.
I also tried to put the correct version of chromInfo with the .fa or my STAR output or Outrigger output, but didn't fix the problem.

**Actual behavior:** [What actually happened]
Time Stamp	Creating folder ./outrigger_output ...
Time Stamp		Done.
Time Stamp	Creating folder ./outrigger_output/index ...
Time Stamp		Done.
Time Stamp	Creating folder ./outrigger_output/index ...
Time Stamp		Done.
Time Stamp	Creating folder ./outrigger_output/index/gtf ...
Time Stamp		Done.
Time Stamp	Creating folder ./outrigger_output/junctions ...
Time Stamp		Done.
Time Stamp	Finding valid splice sites in Skipped Exon (SE) splice type ...
Time Stamp	Creating folder ./outrigger_output/index/se/validated ...
Time Stamp		Done.
Time Stamp		Finding valid splice sites for isoform2 of Skipped Exon events which match GT/AG or GC/AG or AT/AC...
Time Stamp			Finding splice sites for exon1 and exon2 ...
b"ERROR 1146 (42S02) at line 1: Table 'GRCh37.chromInfo' doesn't exist\n"
Commands were:

mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "select chrom, size from GRCh37.chromInfo"
Traceback (most recent call last):
  File "/P/A/T/H/anaconda2/envs/outrigger-env/bin/outrigger", line 6, in <module>
    sys.exit(outrigger.commandline.main())
  File "/P/A/T/H/anaconda2/envs/outrigger-env/lib/python3.5/site-packages/outrigger/commandline.py", line 1071, in main
    cl = CommandLine(sys.argv[1:])
  File "/P/A/T/H/anaconda2/envs/outrigger-env/lib/python3.5/site-packages/outrigger/commandline.py", line 344, in __init__
    self.args.func()
  File "/P/A/T/H/anaconda2/envs/outrigger-env/lib/python3.5/site-packages/outrigger/commandline.py", line 352, in validate
    validate.execute()
  File "/P/A/T/H/anaconda2/envs/outrigger-env/lib/python3.5/site-packages/outrigger/commandline.py", line 834, in execute
    exonA, exonB, splice_abbrev)
  File "/P/A/T/H/anaconda2/envs/outrigger-env/lib/python3.5/site-packages/outrigger/commandline.py", line 787, in exon_pair_splice_sites
    exonA, splice_abbrev, 'downstream')
  File "/P/A/T/H/anaconda2/envs/outrigger-env/lib/python3.5/site-packages/outrigger/commandline.py", line 800, in individual_exon_splice_sites
    exon_bed, self.genome, self.fasta, direction)
  File "/P/A/T/H/anaconda2/envs/outrigger-env/lib/python3.5/site-packages/outrigger/validate/check_splice_sites.py", line 57, in read_splice_sites
    flanked = bed.flank(l=left, r=right, s=True, genome=genome)
  File "/P/A/T/H/anaconda2/envs/outrigger-env/lib/python3.5/site-packages/pybedtools/bedtool.py", line 806, in decorated
    result = method(self, *args, **kwargs)
  File "/P/A/T/H/anaconda2/envs/outrigger-env/lib/python3.5/site-packages/pybedtools/bedtool.py", line 337, in wrapped
    decode_output=decode_output,
  File "/P/A/T/H/anaconda2/envs/outrigger-env/lib/python3.5/site-packages/pybedtools/helpers.py", line 356, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools flank -s -r 2 -l 0 -i ./outrigger_output/index/se/exon1.bed -g /tmp/pybedtools.ghiu8lqg.tmp

Error message was:
ERROR: chrom "14" not found in genome file. Exiting.

### Versions

Ubuntu 14.04
Anaconda 2
Outrigger version 1.1.1 installed with anaconda
Outrigger calls Python 3.5.5 in virtual env created with anaconda

**Comment by fuhao1216** [comment]
> I found the solution..
> 
> After the --genome I put the location of my .chromInfo file and it worked.

HI! What is chrominfo file ,how can i get it

**Comment by liuyu988** [comment]
> I found the solution..
> 
> After the --genome I put the location of my .chromInfo file and it worked.

Hi，would you give the details for getting the .chromInfo? thanks a lot!

**Comment by liuyu988** [comment]
> chromInfo

I suppose that after `-g`, wo should input a genome.chrom.sizes file.
