### ISSUE TITLE
KeyError: junction

### ISSUE THREAD

**Issue by wbvguo** [YeoLab/outrigger#98]
Hi ,I try to use outrigger(version 1.1.1, installed using conda) to calculate the PSI value from bam files. But enconter some error, here is the information about the error

Traceback (most recent call last):
  File "/home/wbguo/apps/anaconda3/envs/outrigger-env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'junction'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wbguo/apps/anaconda3/envs/outrigger-env/bin/outrigger", line 11, in <module>
    load_entry_point('outrigger==1.1.1', 'console_scripts', 'outrigger')()
  File "/home/wbguo/apps/anaconda3/envs/outrigger-env/lib/python3.7/site-packages/outrigger-1.1.1-py3.7.egg/outrigger/commandline.py", line 1071, in main
    cl = CommandLine(sys.argv[1:])
  File "/home/wbguo/apps/anaconda3/envs/outrigger-env/lib/python3.7/site-packages/outrigger-1.1.1-py3.7.egg/outrigger/commandline.py", line 344, in __init__
    self.args.func()
  File "/home/wbguo/apps/anaconda3/envs/outrigger-env/lib/python3.7/site-packages/outrigger-1.1.1-py3.7.egg/outrigger/commandline.py", line 348, in index
    index.execute()
  File "/home/wbguo/apps/anaconda3/envs/outrigger-env/lib/python3.7/site-packages/outrigger-1.1.1-py3.7.egg/outrigger/commandline.py", line 757, in execute
    event_maker = self.make_graph(junction_exon_triples, db)
  File "/home/wbguo/apps/anaconda3/envs/outrigger-env/lib/python3.7/site-packages/outrigger-1.1.1-py3.7.egg/outrigger/commandline.py", line 663, in make_graph
    event_maker = events.EventMaker(junction_exon_triples, db)
  File "/home/wbguo/apps/anaconda3/envs/outrigger-env/lib/python3.7/site-packages/outrigger-1.1.1-py3.7.egg/outrigger/index/events.py", line 288, in __init__
    junction_col].str.split(':').str.get(1)
  File "/home/wbguo/apps/anaconda3/envs/outrigger-env/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/wbguo/apps/anaconda3/envs/outrigger-env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'junction'

Do you have any idea how to solve this?
Thanks in advance

**Comment by pengchy** [comment]
The exact same problem was encountered with bam files produced by hisat2.

**Comment by pilakapa** [comment]
I am also having this problem. I am using sj.out files as input... has anyone found a solution to this problem?
